project:
  type: website
  output-dir: docs

website:
  page-footer: 
    left: "Created with [Quarto](https://quarto.org/) • [Licensed via CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/){target=_blank}" 
    center: "Copyright © 2024 Brandon Morande"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: envelope-fill
        href: mailto:bmorande@uw.edu
      - icon: linkedin
        href: https://www.linkedin.com/in/brandon-morande/
        target: _blank
      - icon: github 
        href: https://github.com/brandonmorande
        target: _blank

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

